//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTestBrowser.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabTestBrowser.Desktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал анализов.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string CommandBar_Back {
            get {
                return ResourceManager.GetString("CommandBar_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        public static string CommandBar_Export {
            get {
                return ResourceManager.GetString("CommandBar_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед.
        /// </summary>
        public static string CommandBar_Forward {
            get {
                return ResourceManager.GetString("CommandBar_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string CommandBar_New {
            get {
                return ResourceManager.GetString("CommandBar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string CommandBar_Save {
            get {
                return ResourceManager.GetString("CommandBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CompleteBloodCount_ExternalId {
            get {
                return ResourceManager.GetString("CompleteBloodCount_ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string CompleteBloodCount_ObservationTimestamp {
            get {
                return ResourceManager.GetString("CompleteBloodCount_ObservationTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить в отчёт.
        /// </summary>
        public static string CompleteBloodCount_Report {
            get {
                return ResourceManager.GetString("CompleteBloodCount_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string CompleteBloodCount_Reset {
            get {
                return ResourceManager.GetString("CompleteBloodCount_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образец.
        /// </summary>
        public static string CompleteBloodCount_SpecimenDescription {
            get {
                return ResourceManager.GetString("CompleteBloodCount_SpecimenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отложить.
        /// </summary>
        public static string CompleteBloodCount_Suppress {
            get {
                return ResourceManager.GetString("CompleteBloodCount_Suppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отложен.
        /// </summary>
        public static string CompleteBloodCount_Suppressed {
            get {
                return ResourceManager.GetString("CompleteBloodCount_Suppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОАК.
        /// </summary>
        public static string CompleteBloodCount_Title {
            get {
                return ResourceManager.GetString("CompleteBloodCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д.
        /// </summary>
        public static string Day_Short {
            get {
                return ResourceManager.GetString("Day_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Лабораторные отчеты/{{DATE}}/Отчет № {{SAMPLE}} от {{DATE}}.
        /// </summary>
        public static string Export_DefaultPath {
            get {
                return ResourceManager.GetString("Export_DefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не сохранены.
        /// </summary>
        public static string LabReport_DataNotSaved {
            get {
                return ResourceManager.GetString("LabReport_DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка экспорта.
        /// </summary>
        public static string LabReport_ExportFailed {
            get {
                return ResourceManager.GetString("LabReport_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт запущен.
        /// </summary>
        public static string LabReport_Exporting {
            get {
                return ResourceManager.GetString("LabReport_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов.
        /// </summary>
        public static string LabReport_Idle {
            get {
                return ResourceManager.GetString("LabReport_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string LabReport_Loading {
            get {
                return ResourceManager.GetString("LabReport_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт завершен.
        /// </summary>
        public static string LabReport_ReportExported {
            get {
                return ResourceManager.GetString("LabReport_ReportExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт не сохранён.
        /// </summary>
        public static string LabReport_ReportNotSaved {
            get {
                return ResourceManager.GetString("LabReport_ReportNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт сохранён.
        /// </summary>
        public static string LabReport_ReportSaved {
            get {
                return ResourceManager.GetString("LabReport_ReportSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить.
        /// </summary>
        public static string LabReport_ReportSavingFailed {
            get {
                return ResourceManager.GetString("LabReport_ReportSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ добавлен в отчёт.
        /// </summary>
        public static string LabReport_TestReported {
            get {
                return ResourceManager.GetString("LabReport_TestReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ сброшен.
        /// </summary>
        public static string LabReport_TestReset {
            get {
                return ResourceManager.GetString("LabReport_TestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ отложен.
        /// </summary>
        public static string LabReport_TestSuppressed {
            get {
                return ResourceManager.GetString("LabReport_TestSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string LabRequisition_Age {
            get {
                return ResourceManager.GetString("LabRequisition_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        public static string LabRequisition_AgeInDays {
            get {
                return ResourceManager.GetString("LabRequisition_AgeInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мес.
        /// </summary>
        public static string LabRequisition_AgeInMonths {
            get {
                return ResourceManager.GetString("LabRequisition_AgeInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лет.
        /// </summary>
        public static string LabRequisition_AgeInYears {
            get {
                return ResourceManager.GetString("LabRequisition_AgeInYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Животное.
        /// </summary>
        public static string LabRequisition_Animal {
            get {
                return ResourceManager.GetString("LabRequisition_Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порода.
        /// </summary>
        public static string LabRequisition_Breed {
            get {
                return ResourceManager.GetString("LabRequisition_Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория/пол.
        /// </summary>
        public static string LabRequisition_CategoryAndSex {
            get {
                return ResourceManager.GetString("LabRequisition_CategoryAndSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата обследования.
        /// </summary>
        public static string LabRequisition_DateOfService {
            get {
                return ResourceManager.GetString("LabRequisition_DateOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медучреждение.
        /// </summary>
        public static string LabRequisition_HealthcareFacility {
            get {
                return ResourceManager.GetString("LabRequisition_HealthcareFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя питомца.
        /// </summary>
        public static string LabRequisition_Nickname {
            get {
                return ResourceManager.GetString("LabRequisition_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        public static string LabRequisition_PetOwner {
            get {
                return ResourceManager.GetString("LabRequisition_PetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать дату.
        /// </summary>
        public static string LabRequisition_PickDate {
            get {
                return ResourceManager.GetString("LabRequisition_PickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string LabRequisition_SatelliteFacility {
            get {
                return ResourceManager.GetString("LabRequisition_SatelliteFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер образца.
        /// </summary>
        public static string LabRequisition_SpecimenNumber {
            get {
                return ResourceManager.GetString("LabRequisition_SpecimenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные образца.
        /// </summary>
        public static string LabRequisition_Title {
            get {
                return ResourceManager.GetString("LabRequisition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        public static string Month_Short {
            get {
                return ResourceManager.GetString("Month_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string ReportTemplateDialog_Cancel {
            get {
                return ResourceManager.GetString("ReportTemplateDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать.
        /// </summary>
        public static string ReportTemplateDialog_Export {
            get {
                return ResourceManager.GetString("ReportTemplateDialog_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string ReportTemplateDialog_Hide {
            get {
                return ResourceManager.GetString("ReportTemplateDialog_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все зарегистрированные шаблоны.
        /// </summary>
        public static string ReportTemplateDialog_RegisteredTemplates {
            get {
                return ResourceManager.GetString("ReportTemplateDialog_RegisteredTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string ReportTemplateDialog_Show {
            get {
                return ResourceManager.GetString("ReportTemplateDialog_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л.
        /// </summary>
        public static string Years_Plural_Short {
            get {
                return ResourceManager.GetString("Years_Plural_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г.
        /// </summary>
        public static string Years_Singular_Short {
            get {
                return ResourceManager.GetString("Years_Singular_Short", resourceCulture);
            }
        }
    }
}
