namespace LabTestBrowser.Infrastructure.Hl7.Messaging.v231;

public static class OBR
{
	public const int Id = 1;
	public const int PlacerOrderNumber = 2;
	public const int FillerOrderNumber = 3;
	public const int UniversalServiceId = 4;
	public const int Priority = 5;
	public const int RequestedDatetime = 6;
	public const int ObservationDateTime = 7;
	public const int ObservationEndDateTime = 8;
	public const int CollectionVolume = 9;
	public const int CollectorIdentifier = 10;
	public const int SpecimenActionCode = 11;
	public const int DangerCode = 12;
	public const int RelevantClinicalInfo = 13;
	public const int SpecimenReceivedDateTime = 14;
	public const int SpecimenSource = 15;
	public const int OrderingProvider = 16;
	public const int OrderCallbackPhoneNumber = 17;
	public const int PlacerField1 = 18;
	public const int PlacerField2 = 19;
	public const int FillerField1 = 20;
	public const int FillerField2 = 21;
	public const int ResultsReportedOrStatusChangedDateTime = 22;
	public const int ChargeToPractice = 23;
	public const int DiagnosticServSectId = 24;
	public const int ResultStatus = 25;
	public const int ParentResult = 26;
	public const int QuantityAndTiming = 27;
	public const int ResultCopiesTo = 28;
	public const int Parent = 29;
	public const int TransportationMode = 30;
	public const int ReasonForStudy = 31;
	public const int PrincipalResultInterpreter = 32;
	public const int AssistantResultInterpreter = 33;
	public const int Technician = 34;
	public const int Transcriptionist = 35;
	public const int ScheduledDateTime = 36;
	public const int NumberOfSampleContainers = 37;
	public const int TransportLogisticsOfCollectedSample = 38;
	public const int CollectorComment = 39;
	public const int TransportArrangementResponsibility = 40;
	public const int TransportArranged = 41;
	public const int EscortRequired = 42;
	public const int PlannedPatientTransportComment = 43;
	public const int ProcedureCode = 44;
	public const int ProcedureCodeModifier = 45;
}